name: hb_mobile2021
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.25+72
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  #  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^2.0.8
  flutter_pdfview: ^1.2.1
  http: ^0.13.4
  #  flutter_form_builder: ^3.13.4
  sticky_headers: ^0.3.0+2
  shared_preferences : any
  #  permission_handler: 4.4.0
  #  dio: any
  #  ext_storage: ^1.0.3
  #flutter_downloader : 1.5.0
  #  permission_handler: 5.0.1
  #  rxdart: ^0.24.1
  flutter_keyboard_visibility: ^5.4.0
  flutter_easyloading: ^3.0.5
  firebase_messaging: ^14.1.4
  flutter_signature_pad: ^3.0.1
  #  image_gallery_saver: ^1.6.6
  image_picker: ^0.8.4+4
  #  save_in_gallery: ^0.1.3
  path: ^1.6.4
  provider: ^6.0.4
  #provider: ^3.0.0+1
  moor_flutter: ^4.0.0
  flutter_slidable: ^2.0.0
  infinite_scroll_pagination: ^3.2.0
  font_awesome_flutter: ^10.3.0
  multiselect_formfield: ^0.1.3
  flutter_multiselect: ^1.0.0
  table_calendar: ^3.0.8
  #  google_sign_in: 4.5.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  # dropdownfield: ^1.0.3
  date_time_picker: ^2.1.0
  list_treeview: ^0.3.0
  flutter_simple_treeview: ^3.0.2
  flutter_treeview: ^1.0.3+2
  #  multi_select_item: ^1.0.3
  #  open_file: ^3.2.1
  #  docx_template: ^0.2.10
  #  flutter_launcher_name: ^0.0.1
  # progress_indicator_button: ^0.0.3
  file_picker: ^5.2.3
  animated_text_kit: ^4.2.1
  flutter_native_splash: ^2.2.16
  json_table: ^2.0.1
  data_table_2: ^2.1.1
  responsive_table: ^0.2.0+2
  get: ^4.3.8
  #  syncfusion_flutter_datagrid: ^19.3.43-beta
  html: ^0.15.0
  js: ^0.6.3
  bordered_text: ^2.0.0
  #  ff_navigation_bar: ^0.1.5
  #  native_pdf_view: ^5.0.0
  #  pdf_flutter: ^1.1.2
  new_version: ^0.3.1
  dio: ^4.0.4
  badges: ^2.0.2
  url_launcher: ^6.0.18
  #  firebase_messaging: ^14.1.3
  #  flutter_local_notifications: ^8.1.1+1
  firebase_core: ^2.3.0
  #show notifiaction
  flutter_local_notifications: ^12.0.4
  #listen for notifiaction
  rxdart: ^0.27.1
  #flutter_filereader: ^3.0.0
  #webview_flutter: ^3.0.0
  percent_indicator: ^4.0.0
  #advance_pdf_viewer: ^2.0.1
  #flutter_full_pdf_viewer: ^1.0.6
  flutter_cached_pdfview: ^0.4.1
  transparent_image: ^2.0.0
  flutter_downloader: ^1.9.1
  permission_handler: ^10.2.0
  flutter_custom_cards: ^0.2.1
  flutter_emoji: ^2.3.3
  intl: ^0.17.0
  firebase_messaging_platform_interface: 4.2.8
  resize: ^1.0.0
  local_auth: ^2.1.6






  #flutter_easyloading: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  #  moor_generator: ^1.5.1
  build_runner:

dependency_overrides:
#  firebase_messaging_platform_interface: 4.2.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_thb.png"
flutter_launcher_name:
  name: "Quản lý văn bản điều hành và tác nghiệp"
flutter_native_splash:
  color: "#42a5f5"
  image: "assets/logo_thb.png"
  android_gravity: fill
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf
          weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
