import 'package:shared_preferences/shared_preferences.dart';
import 'dart:async';
import 'package:http/http.dart' as http;


  Timer _timer;
  String tokenDevice="";
  String tendangnhapAll = "";
  String ten;
  var datavb = "";
  var vanbandenCapNhat = null;
  int trangThaiVB =0;
  int vbdiTrangThaiVB =0;
  int vbdiCurrentNguoiTrinhID =0;
  int vbdiPBLookup =0;
  String vbdiNguoiSoan= "";
  List lstPhongBanLaVanThuVBDI= [];
  List lstPhongBanLaVanThuVBDEN= [];
  List userGroups= [];
  List lstThongTinGroup= [];
  bool ThemMoiVanBanDi= false;
  bool ThemVanBanDen= false;
  bool checkThuHoi= false;
  bool ThietLapHoiBao= false;
  bool vbdiCanTDHB= false;
  bool isTrinhKy= false;
  bool trinhDaCoNgDuyet= false;
  bool trinhLan2= false;
  bool ChuyenVT= false;
  String SiteAction= "";
  String userTenTruyCap= "";
  int vbdiNguoiSoanID= 0;
  int hscvNguoiLap= 0;
  int hscvNguoiPhuTrach= 0;
  int currentUserID= 0;
  int CurrentDonViID= 0;
  List ThongTinLConfig=[];
  int vbdiNguoiKyID= 0;
  int chukyso= 0;
  String vbdiNguoiTrinhTiep= "";
  List vbdiDSNguoiTrinhTiep=[];
  String vbdiNguoiKy= "";
  String hoVaTen = "";
  String tenPhongBan = "";
  String OrganName = "";
  var tick = 0;
  String EmailHT = "";
  String Telephone = "";
  String ngayTrinhDT= "";
  bool butPheVBD = false;
  bool thuHoiVBD = false;
  bool isDuyetVaPhatHanh = false;
  bool kyVaPhatHanh = false;
  bool checkKetThucHSCV = false;
  bool checkSoanVBDT = false;
  bool checkChuyenVaoHS = false;
  bool isDuyetTruongPhong = false;
  bool isGuiVanban = false;
  bool isDuyet = false;
  String XemDB = "";
  bool hanXLVBD = false;
  int vbdTTXuLyVanBanLT= 0;
  int isnguoiduyet= 0;
  int vbdPhuongThuc= 0;
  int vbdTrangThaiXuLyVanBan= 0;
  int vbdSoVanBan= 0;
  int hscvTrangThaiXuLy= 0;
  var  currentDuThao;
  List lstvbdUserChuaXuLy = [];
  List strListId = [];
  List strListVanBanLienQuanID = [];
  List strListVanBanDiLienQuan = [];
  List vbdiCurrentUserReceived = [];
  bool vbdUserChuaXuLy = false;
  String vbdHanXuLy ="";
  bool vbdiIsSentVanBan = false;
  bool ThemMoiVanBanDuThao = false;
  bool isTraCuu = false;
  bool checkbtnXDB = false;
  bool CapSoVanBanDi = false;
  bool vbdIsSentVanBan = false;
  bool clickChon =  false;
  bool GuiVanBanDi = false;
  bool GuiVanBan = false;
  bool SuaVanBanDen = false;
  bool vbdiDSNguoiTrinhTiepKy = false;
  bool isQTNew = false;
  bool notIsQuanTriNew = false;
  bool ispGuiXuLyChinh = false;
  int ID=0;
  int DonViInSiteID=0;
  List<dynamic> userHasQuyenKyVB = [];
  int groupID = 0;
  List duthaoListXoa = [];
//thêm mới dự thảo
  String TrichYeuDT = "";
  String loaivbDT =  "";
  String vbdiSoKyHieu = "";
  String vNguoiKy = "";
  String vNguoiTrinh= "";
  String toTrinh= "";
  String CurrentTenDonVi= "";
  String ls="";
  String ls1="";
  String ls2="";
  String messingCN = "";
  String matKhauHT = "";
  List dataListTT = [];
  var vanbanDi ;
  var vanbanDen = null ;
  var vanbanDT = null ;
  String userChucVu = "";
  String pdf = "";
  String pdfDK = "";
  List Listpdf = [];
  List ListpdfDK = [];
  List ListpdfPT = [];
  String namepdf = "";
  String pdfPT = "";
  String idCT = "";
  String idChuTri = "";
  String idPhoiHop = "";
  String idTheoDoi = "";
  String idNTD = "";
  int IDTT ;
  List chuaPDF = [];
  String tenPDFTruyen ="";
  String imageCK ="";
  double widthKy = 150.0, heightKy = 75.0;


